// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'dgm360';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String DIGI_BACKGROUND = 'assets/images/Digi-Background.jpeg';
  static const String DIGI_LOGO = 'assets/images/Digi-logo.jpeg';
  static const String DIGI_LOGO_PREVIEW = 'assets/images/Digi-logo_preview.png';
}
